// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	ReqTunnel
	ReqTunnelAck
	Pack
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pack_Type int32

const (
	Pack_DATA         Pack_Type = 0
	Pack_SUBCRIBE     Pack_Type = 1
	Pack_SUBCRIBE_ACK Pack_Type = 2
	Pack_REPORT       Pack_Type = 3
	Pack_RELEASE      Pack_Type = 4
)

var Pack_Type_name = map[int32]string{
	0: "DATA",
	1: "SUBCRIBE",
	2: "SUBCRIBE_ACK",
	3: "REPORT",
	4: "RELEASE",
}
var Pack_Type_value = map[string]int32{
	"DATA":         0,
	"SUBCRIBE":     1,
	"SUBCRIBE_ACK": 2,
	"REPORT":       3,
	"RELEASE":      4,
}

func (x Pack_Type) String() string {
	return proto.EnumName(Pack_Type_name, int32(x))
}
func (Pack_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type ReqTunnel struct {
	ClientID uint32 `protobuf:"varint,1,opt,name=ClientID" json:"ClientID,omitempty"`
}

func (m *ReqTunnel) Reset()                    { *m = ReqTunnel{} }
func (m *ReqTunnel) String() string            { return proto.CompactTextString(m) }
func (*ReqTunnel) ProtoMessage()               {}
func (*ReqTunnel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqTunnel) GetClientID() uint32 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

type ReqTunnelAck struct {
	ClientID   uint32 `protobuf:"varint,1,opt,name=ClientID" json:"ClientID,omitempty"`
	TunnelID   uint32 `protobuf:"varint,2,opt,name=TunnelID" json:"TunnelID,omitempty"`
	TunnelPort uint32 `protobuf:"varint,3,opt,name=TunnelPort" json:"TunnelPort,omitempty"`
}

func (m *ReqTunnelAck) Reset()                    { *m = ReqTunnelAck{} }
func (m *ReqTunnelAck) String() string            { return proto.CompactTextString(m) }
func (*ReqTunnelAck) ProtoMessage()               {}
func (*ReqTunnelAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReqTunnelAck) GetClientID() uint32 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func (m *ReqTunnelAck) GetTunnelID() uint32 {
	if m != nil {
		return m.TunnelID
	}
	return 0
}

func (m *ReqTunnelAck) GetTunnelPort() uint32 {
	if m != nil {
		return m.TunnelPort
	}
	return 0
}

type Pack struct {
	Type        Pack_Type         `protobuf:"varint,1,opt,name=type,enum=msg.Pack_Type" json:"type,omitempty"`
	Subcribe    *Pack_Subcribe    `protobuf:"bytes,2,opt,name=subcribe" json:"subcribe,omitempty"`
	SubcribeAck *Pack_SubcribeAck `protobuf:"bytes,3,opt,name=subcribeAck" json:"subcribeAck,omitempty"`
	Report      *Pack_Report      `protobuf:"bytes,4,opt,name=report" json:"report,omitempty"`
	Release     *Pack_Release     `protobuf:"bytes,5,opt,name=release" json:"release,omitempty"`
	Data        *Pack_Data        `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
}

func (m *Pack) Reset()                    { *m = Pack{} }
func (m *Pack) String() string            { return proto.CompactTextString(m) }
func (*Pack) ProtoMessage()               {}
func (*Pack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Pack) GetType() Pack_Type {
	if m != nil {
		return m.Type
	}
	return Pack_DATA
}

func (m *Pack) GetSubcribe() *Pack_Subcribe {
	if m != nil {
		return m.Subcribe
	}
	return nil
}

func (m *Pack) GetSubcribeAck() *Pack_SubcribeAck {
	if m != nil {
		return m.SubcribeAck
	}
	return nil
}

func (m *Pack) GetReport() *Pack_Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *Pack) GetRelease() *Pack_Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *Pack) GetData() *Pack_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Pack_Subcribe struct {
	TunnelID  uint32 `protobuf:"varint,1,opt,name=TunnelID" json:"TunnelID,omitempty"`
	ResouceID string `protobuf:"bytes,2,opt,name=ResouceID" json:"ResouceID,omitempty"`
	Start     uint32 `protobuf:"varint,3,opt,name=Start" json:"Start,omitempty"`
	End       uint32 `protobuf:"varint,4,opt,name=End" json:"End,omitempty"`
}

func (m *Pack_Subcribe) Reset()                    { *m = Pack_Subcribe{} }
func (m *Pack_Subcribe) String() string            { return proto.CompactTextString(m) }
func (*Pack_Subcribe) ProtoMessage()               {}
func (*Pack_Subcribe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Pack_Subcribe) GetTunnelID() uint32 {
	if m != nil {
		return m.TunnelID
	}
	return 0
}

func (m *Pack_Subcribe) GetResouceID() string {
	if m != nil {
		return m.ResouceID
	}
	return ""
}

func (m *Pack_Subcribe) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Pack_Subcribe) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

type Pack_SubcribeAck struct {
	ResouceID  string `protobuf:"bytes,1,opt,name=ResouceID" json:"ResouceID,omitempty"`
	SessionID  uint32 `protobuf:"varint,2,opt,name=SessionID" json:"SessionID,omitempty"`
	IsAccepted bool   `protobuf:"varint,3,opt,name=IsAccepted" json:"IsAccepted,omitempty"`
}

func (m *Pack_SubcribeAck) Reset()                    { *m = Pack_SubcribeAck{} }
func (m *Pack_SubcribeAck) String() string            { return proto.CompactTextString(m) }
func (*Pack_SubcribeAck) ProtoMessage()               {}
func (*Pack_SubcribeAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *Pack_SubcribeAck) GetResouceID() string {
	if m != nil {
		return m.ResouceID
	}
	return ""
}

func (m *Pack_SubcribeAck) GetSessionID() uint32 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

func (m *Pack_SubcribeAck) GetIsAccepted() bool {
	if m != nil {
		return m.IsAccepted
	}
	return false
}

type Pack_Report struct {
	SessionID   uint32 `protobuf:"varint,1,opt,name=SessionID" json:"SessionID,omitempty"`
	TotalRecved uint32 `protobuf:"varint,2,opt,name=TotalRecved" json:"TotalRecved,omitempty"`
	Rate        uint32 `protobuf:"varint,3,opt,name=Rate" json:"Rate,omitempty"`
	RecvedPacks uint32 `protobuf:"varint,4,opt,name=RecvedPacks" json:"RecvedPacks,omitempty"`
	Bitmap      []byte `protobuf:"bytes,5,opt,name=Bitmap,proto3" json:"Bitmap,omitempty"`
}

func (m *Pack_Report) Reset()                    { *m = Pack_Report{} }
func (m *Pack_Report) String() string            { return proto.CompactTextString(m) }
func (*Pack_Report) ProtoMessage()               {}
func (*Pack_Report) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *Pack_Report) GetSessionID() uint32 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

func (m *Pack_Report) GetTotalRecved() uint32 {
	if m != nil {
		return m.TotalRecved
	}
	return 0
}

func (m *Pack_Report) GetRate() uint32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Pack_Report) GetRecvedPacks() uint32 {
	if m != nil {
		return m.RecvedPacks
	}
	return 0
}

func (m *Pack_Report) GetBitmap() []byte {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

type Pack_Release struct {
	TunnelID uint32 `protobuf:"varint,1,opt,name=TunnelID" json:"TunnelID,omitempty"`
}

func (m *Pack_Release) Reset()                    { *m = Pack_Release{} }
func (m *Pack_Release) String() string            { return proto.CompactTextString(m) }
func (*Pack_Release) ProtoMessage()               {}
func (*Pack_Release) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 3} }

func (m *Pack_Release) GetTunnelID() uint32 {
	if m != nil {
		return m.TunnelID
	}
	return 0
}

type Pack_Data struct {
	SessionID uint32 `protobuf:"varint,1,opt,name=SessionID" json:"SessionID,omitempty"`
	Index     uint32 `protobuf:"varint,2,opt,name=Index" json:"Index,omitempty"`
	Payload   []byte `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (m *Pack_Data) Reset()                    { *m = Pack_Data{} }
func (m *Pack_Data) String() string            { return proto.CompactTextString(m) }
func (*Pack_Data) ProtoMessage()               {}
func (*Pack_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 4} }

func (m *Pack_Data) GetSessionID() uint32 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

func (m *Pack_Data) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Pack_Data) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqTunnel)(nil), "msg.ReqTunnel")
	proto.RegisterType((*ReqTunnelAck)(nil), "msg.ReqTunnelAck")
	proto.RegisterType((*Pack)(nil), "msg.Pack")
	proto.RegisterType((*Pack_Subcribe)(nil), "msg.Pack.Subcribe")
	proto.RegisterType((*Pack_SubcribeAck)(nil), "msg.Pack.SubcribeAck")
	proto.RegisterType((*Pack_Report)(nil), "msg.Pack.Report")
	proto.RegisterType((*Pack_Release)(nil), "msg.Pack.Release")
	proto.RegisterType((*Pack_Data)(nil), "msg.Pack.Data")
	proto.RegisterEnum("msg.Pack_Type", Pack_Type_name, Pack_Type_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x8b, 0x9b, 0x50,
	0x14, 0xad, 0x13, 0xc7, 0x98, 0x6b, 0x66, 0xb0, 0x97, 0x69, 0x11, 0x19, 0xca, 0x10, 0x28, 0x1d,
	0x28, 0x64, 0x91, 0x2e, 0xba, 0x36, 0x89, 0x0b, 0x69, 0xa1, 0xe1, 0x6a, 0xd7, 0xe5, 0x45, 0x5f,
	0x07, 0x89, 0x51, 0xab, 0x2f, 0xa5, 0xf9, 0x23, 0xfd, 0x4d, 0xfd, 0x59, 0xe5, 0x3d, 0x3f, 0x62,
	0x52, 0x98, 0xee, 0xde, 0x3d, 0xe7, 0xdc, 0xaf, 0x73, 0x15, 0x26, 0xfb, 0xfa, 0x69, 0x5e, 0x56,
	0x85, 0x28, 0x70, 0xb4, 0xaf, 0x9f, 0x66, 0xef, 0x60, 0x42, 0xfc, 0x47, 0x74, 0xc8, 0x73, 0x9e,
	0xa1, 0x0b, 0xe6, 0x2a, 0x4b, 0x79, 0x2e, 0x82, 0xb5, 0xa3, 0x3d, 0x68, 0x8f, 0x37, 0xd4, 0xc7,
	0xb3, 0xef, 0x30, 0xed, 0x85, 0x5e, 0xbc, 0x7b, 0x4e, 0x2b, 0xb9, 0x46, 0x18, 0xac, 0x9d, 0xab,
	0x86, 0xeb, 0x62, 0x7c, 0x03, 0xd0, 0xbc, 0x37, 0x45, 0x25, 0x9c, 0x91, 0x62, 0x07, 0xc8, 0xec,
	0x8f, 0x01, 0xfa, 0x86, 0xc5, 0x3b, 0x9c, 0x81, 0x2e, 0x8e, 0x25, 0x57, 0xc5, 0x6f, 0x17, 0xb7,
	0x73, 0x39, 0xb8, 0x24, 0xe6, 0xd1, 0xb1, 0xe4, 0xa4, 0x38, 0x9c, 0x83, 0x59, 0x1f, 0xb6, 0x71,
	0x95, 0x6e, 0xb9, 0x6a, 0x64, 0x2d, 0xf0, 0xa4, 0x0b, 0x5b, 0x86, 0x7a, 0x0d, 0x7e, 0x04, 0xab,
	0x7b, 0x7b, 0xf1, 0x4e, 0x75, 0xb7, 0x16, 0xaf, 0xfe, 0x4d, 0xf1, 0xe2, 0x1d, 0x0d, 0x95, 0xf8,
	0x08, 0x46, 0xc5, 0x4b, 0x39, 0xb1, 0xae, 0x72, 0xec, 0x53, 0x0e, 0x29, 0x9c, 0x5a, 0x1e, 0xdf,
	0xc3, 0xb8, 0xe2, 0x19, 0x67, 0x35, 0x77, 0xae, 0x95, 0xf4, 0xe5, 0x50, 0xaa, 0x08, 0xea, 0x14,
	0x72, 0xc7, 0x84, 0x09, 0xe6, 0x18, 0x4a, 0x39, 0xd8, 0x71, 0xcd, 0x04, 0x23, 0xc5, 0xb9, 0x19,
	0x98, 0xdd, 0x58, 0x67, 0xc6, 0x6a, 0x17, 0xc6, 0xde, 0xcb, 0x4b, 0xd6, 0xc5, 0x21, 0xe6, 0xad,
	0xeb, 0x13, 0x3a, 0x01, 0x78, 0x07, 0xd7, 0xa1, 0x60, 0xbd, 0xe3, 0x4d, 0x80, 0x36, 0x8c, 0xfc,
	0x3c, 0x51, 0x3b, 0xdd, 0x90, 0x7c, 0xba, 0x29, 0x58, 0x03, 0x13, 0xce, 0x8b, 0x6a, 0x97, 0x45,
	0xef, 0x61, 0x12, 0xf2, 0xba, 0x4e, 0x8b, 0xbc, 0x3f, 0xf4, 0x09, 0x90, 0x97, 0x0e, 0x6a, 0x2f,
	0x8e, 0x79, 0x29, 0x78, 0xa2, 0xfa, 0x9a, 0x34, 0x40, 0xdc, 0xdf, 0x1a, 0x18, 0x8d, 0x79, 0xe7,
	0x85, 0xb4, 0xcb, 0x42, 0x0f, 0x60, 0x45, 0x85, 0x60, 0x19, 0xf1, 0xf8, 0x27, 0x4f, 0xda, 0x46,
	0x43, 0x08, 0x11, 0x74, 0x62, 0x82, 0xb7, 0xcb, 0xa9, 0xb7, 0xcc, 0x6a, 0x58, 0x69, 0x68, 0xdd,
	0xee, 0x38, 0x84, 0xf0, 0x35, 0x18, 0xcb, 0x54, 0xec, 0x59, 0xa9, 0x2e, 0x35, 0xa5, 0x36, 0x72,
	0xdf, 0xc2, 0xb8, 0xbd, 0xd4, 0x73, 0x86, 0xbb, 0x11, 0xe8, 0xf2, 0x4c, 0xff, 0x19, 0xfe, 0x0e,
	0xae, 0x83, 0x3c, 0xe1, 0xbf, 0xda, 0xb1, 0x9b, 0x00, 0x1d, 0x18, 0x6f, 0xd8, 0x31, 0x2b, 0x58,
	0x63, 0xcc, 0x94, 0xba, 0x70, 0x16, 0x80, 0x2e, 0x3f, 0x70, 0x34, 0x41, 0x5f, 0x7b, 0x91, 0x67,
	0xbf, 0xc0, 0x29, 0x98, 0xe1, 0xd7, 0xe5, 0x8a, 0x82, 0xa5, 0x6f, 0x6b, 0x68, 0xc3, 0xb4, 0x8b,
	0xbe, 0x79, 0xab, 0x4f, 0xf6, 0x15, 0x02, 0x18, 0xe4, 0x6f, 0xbe, 0x50, 0x64, 0x8f, 0xd0, 0x82,
	0x31, 0xf9, 0x9f, 0x7d, 0x2f, 0xf4, 0x6d, 0x7d, 0x6b, 0xa8, 0xff, 0xfc, 0xc3, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd9, 0x43, 0xa9, 0x7a, 0xf4, 0x03, 0x00, 0x00,
}
